#!/bin/bash
[D[D[D[A[A[C[C[C[B[C[C[C[C[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D[$ ls
[A[C[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
[A[A[A[C[C[C[C[C[C[C[C[C[C[C[A[C[B[D[D[D[D[D
